### PR TITLE
[Blog Post] UI Design Trends 2020

### PR DESCRIPTION
**Pull request by meissadia**
Target post date: Tueday, March 10, 2020

blog-ui-trends

### CODE REVIEW

**Comment by meissadia** [comment]
Confirmed a target post date of Tuesday, March 10, 2020 with @RedNumberIX.  

Based on my local testing, it seems like this can be merged in anytime but will not display on the site until the date in the post title `_posts/2020-03-10-ui-design-trends.md`.  @BarakStout does that sound right?

**Comment by BarakStout** [comment]
Correct @meissadia by default, future posts will not be generated. This doesn't mean that it will get publish auto-magically. GitHub generates the site when there is a new commit. We can merge it and trigger it manually or use a `published` flag in the front-matter. I think that's a safer approach. [More about future posts](http://sangsoonam.github.io/2018/12/27/writing-upcoming-posts-in-github-pages.html)

**Comment by meissadia** [comment]
@BarakStout Hmm. `force push` to master is disabled.  And flipping the `published` flag for a post would require review/merge, same as just merging the Blog post on the day it should go live.  

So I think it would be easiest for reviewers to approve, then have the PR creator be responsible for merging on the publishing date.

**Comment by BarakStout** [comment]
For now, I think the reviewer can merge, as long as the target time is in the PR as a comment. There are ways to set future publish times and have it auto-deploy. I will add it as to-do ticket.

**Comment by meissadia** [comment]
@BarakStout 

> How do we feel about the size of the picture? Can they be scaled down?

Great catch.  I swore I had shrunk the bgimg because it was huge.  Also converted the larger `pngs` to `jpgs`.

**Pull request merged**
