### PR TITLE
Added four new sketches to the website

### PR DESCRIPTION
**Pull request by MissyM2**
* added pictures of Jack Bevis, Marc Phillips, Missy Maloney and Rebecca Mancuso to the _About_ page.  They already had profile text.

* reviewed the page and everything works properly.
Screen Shot 2020-11-03 at 10 42 41 AM

### CODE REVIEW

**Review by meissadia — CHANGES_REQUESTED** [review]
- [ ] Please adjust the dimensions of new images to a max of 1000x1000.  The largest size we display on the site is 400x400, but having them at 1000x1000 allows larger display in the future without having to regenerate the images. 
  Screen Shot 2020-11-03 at 11 21 05 AM  

- [ ] Optimize the image file sizes (~100kb great, under 200kb is ok).  Some of these images are 2MB+ which is way too large for web graphics.  Optimization can be achieved by one or more of the following:
  - Lowering the image quality (I usually use the Preview app on my Mac: File -> Export -> Quality)
  - Use tinyjpg.com

- [ ] Delete duplicate image for Carl (either `Carl.png` or `carl_smith.png`)
- [ ] Delete unused images `Beata.jpg`, `Leslie.jpg`, `Missy.jpg`
- [ ] Delete Ryan Hunter's profile and image

**Comment by MissyM2** [comment]
@meissadia In addition to the above, I added Paul's picture/profile text and links.  I also changed all the image names to *firstname_lastname*.  A couple of questions:
- do you want me to change all the images to .jpg?
- is there a particular order that you want to follow with the members?

**Comment by meissadia** [comment]
@MissyM2 No need to change the formats right now.  Maybe that can be added to https://github.com/raft-tech/raft-tech.github.io/issues/171

I don't have a preference for the order.

**Review by meissadia — APPROVED** [review]
Looks great, nice work!  :shipit:

**Pull request merged**
