### PR TITLE
Blog post for plain language

### PR DESCRIPTION
**Pull request by turbomarc**
Plain Language blog post

### CODE REVIEW

**Comment by BarakStout** [comment]
We should update the date and unbold the links to be consistent with our other blog posts.

**Review by BarakStout — CHANGES_REQUESTED** [review]
Links in `.md` should not be bold

**Comment by MissyM2** [comment]
@BarakStout Can you clarify your comment?  The bolding/italics is because there is a title of a book or an organization.  Is this particular to .md or is this stylistic?

**Comment by BarakStout** [comment]
> @BarakStout Can you clarify your comment? The bolding/italics is because there is a title of a book or an organization. Is this particular to .md or is this stylistic?

Stylistic to match other links in posts.

**Review by BarakStout — APPROVED** [review]
LGTM 👍

**Pull request merged**
